fonemy_spółgłoskowe = {"b": ("P~", "B"),
                       "bi": ("PJ~", "BW"),
                       "c": ("ZT", "C"),
                       "ci": ("ZTJ", "CW"),
                       "ch": ("X", "CB"),
                       "chi": ("XJ", "CBW"),
                       "cz": ("PV", "CL"),
                       "czi": ("PVJ", "CLW"),
                       "ć": ("TJ", "TW"),
                       "d": ("T~", "BT"),
                       "di": ("TJ~", "BTW"),
                       "dz": ("ZT~", "C"),  # Dodałem
                       "dzi": ("ZTJ~", "CW"),  # Dodałem
                       "dź": ("ZTJ~", "LST"),
                       "dż": ("PV~", "CLW"),
                       "f": ("F", "W"),
                       "fi": ("FJ", "W"),
                       "g": ("K~", "G"),
                       "gi": ("KJ~", "GW"),
                       "h": ("X~", "CBW"),  # Zamieniłem z XK~
                       "hi": ("XJ~", "CBW"),  # Zamieniłem z XKJ~
                       "j": ("J", "CR"),
                       "ji": ("J", "CRW"),
                       "k": ("K", "GW"),
                       "ki": ("KJ", "GW"),
                       "l": ("L", "L"),
                       "li": ("LJ", "LW"),
                       "ł": ("LJ", "LB"),
                       "łi": ("LJ", "LBW"),
                       "m": ("KP", "CS"),
                       "mi": ("KPJ", "CSW"),
                       "n": ("TV", "CL"),
                       "ni": ("TVJ", "CLW"),
                       "ń": ("TVJ", "CLW"),
                       # Tu zmieniłem prawą, bo nie ma "P" po prawej stronie
                       "p": ("P", "RG"),
                       "pi": ("PJ", "RGW"),
                       "q": ("KV", "GWY"),
                       "r": ("R", "R"),
                       "ri": ("RJ", "RW"),
                       "rz": ("RJ", "RBW"),
                       "s": ("S", "S"),
                       "si": ("SJ", "SW"),
                       "sz": ("TP", "RB"),
                       "ś": ("SJ", "SW"),
                       "t": ("T", "T"),
                       "ti": ("TJ", "TW"),
                       "v": ("V", "W"),
                       "vi": ("VJ", "W"),
                       "w": ("V", "W"),
                       "wi": ("VJ", "~W"),
                       "x": ("SK", "BSG"),
                       "xi": ("SKJ", "BSGW"),
                       "z": ("Z", "BS"),
                       "zi": ("ZJ", "BSW"),
                       "ź": ("ZJ", "BSW"),
                       "ż": ("TP~", "RBW")}
